name: Deploy webapp to GitHub Pages

on:
    push:
        branches:
            - main
        paths:
            - src/**
            - public
            - package.json
            - .github/**

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "18"

            - name: Install dependencies
              run: npm ci

            - name: Build project
              run: npm run build-dist

            - name: Echo current directory
              run: |
                pwd
                ls

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v4
              if: github.ref == 'refs/heads/main'
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist
